### ISSUE TITLE
Custom mod files won't copy correctly.

### ISSUE THREAD

**Issue by Miepee** [Lojemiru/AM2R-Autopatcher-Linux#14]
Currently, it is hardcoded, that in the patch_files/files_to_copy folder, only ogg files, the lang folder, the mod folder, txt files, the modifiers.ini file, the icon.png and splash.png are copied over. This creates a problem for custom mods, who use custom files, that are not listed here.

A solution for that, would be to just copy the whole files_to_copy folder over, instead of splitting it into more tasks.

**Comment by Miepee** [comment]
A potential solution could be, to distribute extracted AppImages.
This is very hacky however, and I'd rather avoid it.

**Comment by Lojemiru** [comment]
Fixed in 1eb5039
