### ISSUE TITLE
Cannot run, GL-related segfault

### ISSUE THREAD

**Issue by Sanaki** [Lojemiru/AM2R-Autopatcher-Linux#23]
Much as I'd love to give this a spin, it segfaults immediately on attempting to start (as an AppImage). Tail of the output as follows:
```
Create Window
Display Size(Pixels): 1920,1080
GameDisplayName=AM2R
Win #1
XF86VidModeExtension-Version 2.2
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Only Singlebuffered Visual!
glX-Version 1.4
Segmentation fault (core dumped)
```

Running it through gdb, I got this:
```
Thread 1 "AM2R" received signal SIGSEGV, Segmentation fault.
0xf7d1160a in glXCreateContext () from /tmp/.mount_AM2R.AaRhnp0/usr/lib32/libGL.so.1
```
GPU is a GTX 1060 6GB, running the proprietary 460.56 driver. Haven't encountered this sort of issue with anything else. Any thoughts?

**Comment by Lojemiru** [comment]
What installation type did you use - manual or AppImage?

**Comment by Sanaki** [comment]
AppImage, as stated. Manual isn't viable due to my system's reliance on libcurl4.

**Comment by Lojemiru** [comment]
My bad! Looks like my reading comprehension isn't up to par today :(

That's fine, the AppImage should generally be more compatible. We'll get back to you when our Linux specialist has time to review this; I've got enough knowledge to get the game to compile but the AppImage/NVIDIA shenanigans are still above my head.

**Comment by Lojemiru** [comment]
Alright, we're going to need some more information. Could you please share the output of neofetch?

**Comment by Miepee** [comment]
Hi, could you also try to do this?

1. check with `sudo ldconfig -p | grep -i gl.so` if any of your ilbGL packages point to mesa. If they do, remove the package with `sudo rm /path/to/mesa/package`. Try again now if it works. if it doesn't, do the second step
2. uninstall and reinstall the nvidida drivers (don't forget the 32-bit version! This is often noted with either `32`, `i386` or `i686`) from your local package manager. If that still fails, try installing an older version of the driver.

**Comment by Sanaki** [comment]
No mesa libraries showed up matching that string. The only mesa packages I have installed are either build deps (this is my build machine in addition to my gaming machine) or deps of mandatory packages (such as libglx-mesa0 being a dependency of my DE). At a glance, it seems to install those all into /usr/share/bug/ for whatever reason anyway, so no issue there.

Reinstall didn't get me anywhere, and unfortunately reverting to an old version won't be viable, since older versions are subject to [this bug](https://devtalk.nvidia.com/default/topic/1044496/linux/hangs-freezes-when-vulkan-v-sync-vk_present_mode_fifo_khr-is-enabled/) on my system, which makes my workflow entirely unusable. I'd have to revert a couple years of versions, which would break other more critical tasks due to missing vulkan extensions. For what it's worth though, I believe the last time I tried this out was on 440.66.17, with the same result.

Neofetch info:
```
OS: Linux Mint 19.3 Tricia x86_64 
Host: Inspiron 7577 
Kernel: 5.4.0-66-generic 
Uptime: 33 mins 
Packages: 71735 (apt), 25 (flatpak) 
Shell: bash 4.4.20 
Resolution: 1920x1080 
DE: Cinnamon 4.4.8 
WM: Mutter (Muffin) 
WM Theme: Carta (Mint-Y-Dark) 
Theme: Mint-Y-Darker [GTK2/3] 
Icons: Mint-Y [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-7300HQ (4) @ 3.500GHz 
GPU: NVIDIA GeForce GTX 1060 Mobile 
GPU: Intel HD Graphics 630 
Memory: 8369MiB / 31982MiB 
```

**Comment by Miepee** [comment]
Is your system a laptop?

**Comment by Sanaki** [comment]
It is, yes.

**Comment by Miepee** [comment]
Oh, we had multiple issues with am2r on linux laptops :/

Can you try running am2r via the integrated gpu?

**Comment by Sanaki** [comment]
The iGPU is actually disabled. I don't use bumblebee due to issues in the past, some related to the bug I linked. I could try, but that's going to take enough time to get working that it'll be a while before I'd be able to get back to you.

**Comment by Miepee** [comment]
@Sanaki I may have a fix for you.
Can you try to run it with the `LD_PRELOAD=/usr/lib32/libGL.so` environment variable?

**Comment by Sanaki** [comment]
Bingo. Kinda. In my case it was `LD_PRELOAD=/usr/lib/i386-linux-gnu/libGL.so.1 ./AM2R.AppImage`, but it launched correctly that way. Thank you.

**Comment by Sanaki** [comment]
Mind you, I closed the issue, but if there's a way to make that automatic somehow, that'd definitely be preferable, and would undoubtedly help other users as well. I have no 32-bit `libGL.so` (presumably because it causes conflicts of some sort), but I do have 32-bit `libGL.so.1` symlinked to `libGL.so.1.7.0`, and as mentioned, preloading that works just fine.

**Comment by Lojemiru** [comment]
There's not a great way to automate these kind of preload flags (that we're currently aware of), as various systems could require totally different sets of them and we don't have a straightforward way to tell which ones are required. However, the Linux build of the [AM2RLauncher](https://github.com/AM2R-Community-Developers/AM2RLauncher/releases/latest) has a field for launching with custom flags, which could make this a lot easier to set up for the end user once we get some better documentation up.
