### ISSUE TITLE
Guide: Make AM2R more portable

### ISSUE THREAD

**Issue by ludvigng** [Lojemiru/AM2R-Autopatcher-Linux#25]
Hello!

I've been looking into a way to make the game more portable for linux by including a lot of the system libs in the appimage, with the goal of minimizing what the user needs to install. With these instructions, it completely eliminates the need for the multilib repository in arch linux.

User will only need to install the following package: **lib32-glibc** (`libc6-i386` in ubuntu, `glibc.i686` in fedora)

First a warning, this will mix current and old libs and is kind of a hacky solution. Someone more experienced can probably do a better job of matching proper lib versions and removing some of the unnecessary stuff, I basically just included everything marked as a dependency in pacman for `lib32-libpulse`, along with checking stuff with `ldd`.

You'll need to extract `libgcc_s.so` `libgcc_s.so.1` `libstdc++.so` `libstdc++.so.6` `libstdc++.so.6.0.29` from `lib32-gcc-libs` and place them in the the lib32 folder in `AM2R-Autopatcher-Linux-master/data/AM2R.AppDir/usr/`. You'll also need the libs from the following packages:
> lib32-alsa-lib
lib32-alsa-plugins
lib32-dbus
lib32-flac
lib32-libasyncns
lib32-libcap
lib32-libgcrypt
lib32-libgpg-error
lib32-libogg
lib32-libpulse
lib32-libsndfile
lib32-libvorbis
lib32-openal
lib32-opus
lib32-systemd
lib32-xz
lib32-zstd

You also need to move `pulseaudio/libpulsecommon-15.0.so` to the `lib32` folder to make audio work, otherwise libpulse doesn't seem to find it and you'll get openal errors when running the appimage.

Finally just run the patcher as normal and everything should work.

E: Cleaned up a lot of the packages, because I was using an old version of the autopatcher. Oops!

**Comment by ludvigng** [comment]
I've successfully tested an appimage created this way in a live environment on both Fedora workstation 34 on a dual-gpu laptop (intel/nvidia) and a single gpu desktop (nouveau driver) Solus 4.3. As long as the version of glibc on the running system isn't older than the one used on the bundled libs, it seems to work fine once you install the 32-bit glibc (glibc.i686 on fedora, glibc-32bit on solus). Sound and everything just works without needing to install anything else.

Installing the proprietary nvidia driver in solus on the single gpu system does cause the appimage to segfault though, so I need to do more testing on that one.

**Comment by Miepee** [comment]
Appreciate the effort you took into this, but due to the hacky nature involved, and this kinda being the wrong place for guides, I'll go ahead and close the issue.
