### ISSUE TITLE
Image fails to run

### ISSUE THREAD

**Issue by RancidJackalope** [Lojemiru/AM2R-Autopatcher-Linux#32]
```
$ ./AM2R.AppImage
/tmp/.mount_AM2R.Ak3MabT/bin//runner: 5: Bad substitution
/tmp/.mount_AM2R.Ak3MabT/bin//runner: 5: exec: /.runner-unwrapped: not found
$ chmod +x ./.runner-unwrapped 
$ ./.runner-unwrapped 
./.runner-unwrapped: error while loading shared libraries: libXxf86vm.so.1: cannot open shared object file: No such file or directory
```

patcher.sh log: `https://pastebin.com/raw/uKTdxBCW`

I don't know what's going on.

------------------------------------------------------------------------------
commit df69e1a36900cc493f431b5d7949eb0a0376761e
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

**Comment by Miepee** [comment]
Do you have `libgl1:i386` installed?

Also, what is your shell?

(also, next time you can just send the patsher log in a normal code block, makes it easier for properity, as pastebins can just vanish)

**Comment by Miepee** [comment]
I also just published a commit that fixes your first issue (with the AppImage unable to execute the correct file)

**Comment by RancidJackalope** [comment]
> Do you have `libgl1:i386` installed?

Yes, I have it installed. I don't have that error anymore. What I'm missing is `libcrypto.so.1.0.0` and `libssl.so.1.0.0` which are not in my distro but I'm using the ones provided in this repository, so no problem anymore on that front either.

> Also, what is your shell?
```
$ bash --version | head -1
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
```
But:
```
$ realpath /usr/bin/sh
/usr/bin/dash
```
dash has version: `0.5.11+git20210903+057cd650a4ed-3build1`

> (also, next time you can just send the patsher log in a normal code block, makes it easier for properity, as pastebins can just vanish)

Got it

I updated to `d34314b7073f10b3dcf0a9e2eabe8404cfd266de` and I'm still having the same error:
```
./AM2R.AppImage
/tmp/.mount_AM2R.AErIW87/bin//runner: 5: Bad substitution
/tmp/.mount_AM2R.AErIW87/bin//runner: 5: exec: /.runner-unwrapped: not found
```
Just so you know, I tried `./.runner-unwrapped` now and it runs with your libraries that I'm missing, but I had no sound. I got spammed:
```
OpenAL error: 40964 (SoundHardware::Tick)
OpenAL error: 40964 (Audio_Tick Start)
OpenAL error: 40964 (Audio_Tick End)
```
I searched around and fixed it by installing `libpulse0:i386`, so that's another dependency to list.

**Comment by Miepee** [comment]
> but I'm using the ones provided in this repository, so no problem anymore on that front either.

They should be in the AppImage, but saw down below that it doesn't work for you yet.

> so that's another dependency to list.

yeah, there is a full dependency list on the [AM2RLauncher wiki](https://github.com/AM2R-Community-Developers/AM2RLauncher/wiki/Installation-Process#dependencies-1), thanks for the reminder to backport some of stuff there to here.
Libpulse also is something that is currently required by the host, as we had some problems when it was embedded in the AppImage, see #22 


> I updated to d34314b7073f10b3dcf0a9e2eabe8404cfd266de and I'm still having the same error:

That's strange. Can you try to save the following file:
`foo.sh`
```bash
#!/usr/bin/env bash
echo "${BASH_SOURCE[0]}"
```
and then execute it?

**Comment by RancidJackalope** [comment]
My bad... I missed that wiki link. But in the end I'm not missing dependencies.

> see https://github.com/AM2R-Community-Developers/AM2R-Autopatcher-Linux/issues/22

I read the issue and this is what I did (it works for me). I got rid of all dependencies. Then I made the following directory alongside `./.runner-unwrapped`:
EDIT: This is the full list of dependencies.
```
usr
├── lib
│   └── i386-linux-gnu
│       ├── libpulse-simple.so.0 -> libpulse-simple.so.0.1.1
│       ├── libpulse-simple.so.0.1.1
│       ├── libpulse.so.0 -> libpulse.so.0.24.1
│       ├── libpulse.so.0.24.1
│       └── pulseaudio
│           └── libpulsecommon-15.99.so
├── lib32
│   ├── libasn1.so.8
│   ├── libasound.so.2 -> libasound.so.2.0.0
│   ├── libasound.so.2.0.0
│   ├── libbsd.so.0
│   ├── libcom_err.so.2
│   ├── libcrypto.so.1.0.0
│   ├── libcrypt.so.1
│   ├── libc.so.6
│   ├── libcurl.so.4
│   ├── libdl.so.2
│   ├── libedit.so.2
│   ├── libelf.so.1
│   ├── libexpat.so.1
│   ├── libffi.so.6
│   ├── libgcc_s.so.1
│   ├── libGLdispatch.so.0 -> libGLdispatch.so.0.0.0
│   ├── libGLdispatch.so.0.0.0
│   ├── libGL.so.1 -> libGL.so.1.7.0
│   ├── libGL.so.1.7.0
│   ├── libGLU.so.1
│   ├── libGLX.so.0 -> libGLX.so.0.0.0
│   ├── libGLX.so.0.0.0
│   ├── libgmp.so.10
│   ├── libgnutls.so.30
│   ├── libgssapi_krb5.so.2
│   ├── libgssapi.so.3
│   ├── libhcrypto.so.4
│   ├── libheimbase.so.1
│   ├── libheimntlm.so.0
│   ├── libhogweed.so.4
│   ├── libhx509.so.5
│   ├── libidn.so.11
│   ├── libk5crypto.so.3
│   ├── libkeyutils.so.1
│   ├── libkrb5.so.26
│   ├── libkrb5.so.3
│   ├── libkrb5support.so.0
│   ├── liblber-2.4.so.2
│   ├── libldap_r-2.4.so.2
│   ├── libmd.so.0 -> libmd.so.0.0.5
│   ├── libmd.so.0.0.5
│   ├── libm.so.6
│   ├── libnettle.so.6
│   ├── libopenal.so.1 -> libopenal.so.1.19.1
│   ├── libopenal.so.1.19.1
│   ├── libOpenGL.so.0 -> libOpenGL.so.0.0.0
│   ├── libOpenGL.so.0.0.0
│   ├── libp11-kit.so.0
│   ├── libpciaccess.so.0
│   ├── libpthread.so.0
│   ├── libpulsecommon-15.99.so -> ../lib/i386-linux-gnu/pulseaudio/libpulsecommon-15.99.so
│   ├── libpulse-simple.so.0 -> ../lib/i386-linux-gnu/libpulse-simple.so.0.1.1
│   ├── libpulse-simple.so.0.1.1 -> ../lib/i386-linux-gnu/libpulse-simple.so.0.1.1
│   ├── libpulse.so.0 -> ../lib/i386-linux-gnu/libpulse.so.0.24.1
│   ├── libpulse.so.0.24.1 -> ../lib/i386-linux-gnu/libpulse.so.0.24.1
│   ├── libroken.so.18
│   ├── librtmp.so.1
│   ├── librt.so.1
│   ├── libsasl2.so.2
│   ├── libsensors.so.4
│   ├── libsndio.so.7 -> libsndio.so.7.1
│   ├── libsndio.so.7.1
│   ├── libsqlite3.so.0
│   ├── libssl.so.1.0.0
│   ├── libstdc++.so.6 -> libstdc++.so.6.0.30
│   ├── libstdc++.so.6.0.30
│   ├── libtasn1.so.6
│   ├── libtinfo.so.5
│   ├── libwind.so.0
│   ├── libX11.so.6 -> libX11.so.6.4.0
│   ├── libX11.so.6.4.0
│   ├── libXau.so.6 -> libXau.so.6.0.0
│   ├── libXau.so.6.0.0
│   ├── libxcb.so.1 -> libxcb.so.1.1.0
│   ├── libxcb.so.1.1.0
│   ├── libXdmcp.so.6 -> libXdmcp.so.6.0.0
│   ├── libXdmcp.so.6.0.0
│   ├── libXext.so.6
│   ├── libXfixes.so.3
│   ├── libXrandr.so.2
│   ├── libXrender.so.1
│   ├── libXxf86vm.so.1
│   └── libz.so.1
└── share
    ├── applications
    │   └── AM2R.desktop
    ├── doc
    │   ├── libasn1-8-heimdal
    │   │   └── copyright
    │   ├── libbsd0
    │   │   └── copyright
    │   ├── libc6
    │   │   └── copyright
    │   ├── libcurl3
    │   │   └── copyright
    │   ├── libdrm-amdgpu1
    │   │   └── copyright
    │   ├── libdrm-intel1
    │   │   └── copyright
    │   ├── libdrm-nouveau2
    │   │   └── copyright
    │   ├── libdrm-radeon1
    │   │   └── copyright
    │   ├── libedit2
    │   │   └── copyright
    │   ├── libelf1
    │   │   └── copyright
    │   ├── libffi6
    │   │   └── copyright
    │   ├── libglu1-mesa
    │   │   └── copyright
    │   ├── libgnutls30
    │   │   └── copyright
    │   ├── libgssapi3-heimdal
    │   │   └── copyright
    │   ├── libgssapi-krb5-2
    │   │   └── copyright
    │   ├── libhcrypto4-heimdal
    │   │   └── copyright
    │   ├── libheimbase1-heimdal
    │   │   └── copyright
    │   ├── libheimntlm0-heimdal
    │   │   └── copyright
    │   ├── libhogweed4
    │   │   └── copyright
    │   ├── libhx509-5-heimdal
    │   │   └── copyright
    │   ├── libidn11
    │   │   └── copyright
    │   ├── libk5crypto3
    │   │   └── copyright
    │   ├── libkeyutils1
    │   │   └── copyright
    │   ├── libkrb5-26-heimdal
    │   │   └── copyright
    │   ├── libkrb5-3
    │   │   └── copyright
    │   ├── libkrb5support0
    │   │   └── copyright
    │   ├── libldap-2.4-2
    │   │   └── copyright
    │   ├── libllvm6.0
    │   │   └── copyright
    │   ├── libnettle6
    │   │   └── copyright
    │   ├── libopenal1
    │   │   └── copyright
    │   ├── libpciaccess0
    │   │   └── copyright
    │   ├── libroken18-heimdal
    │   │   └── copyright
    │   ├── librtmp1
    │   │   └── copyright
    │   ├── libsasl2-2
    │   │   └── copyright
    │   ├── libsensors4
    │   │   └── copyright
    │   ├── libsqlite3-0
    │   │   └── copyright
    │   ├── libssl1.0.0
    │   │   └── copyright
    │   ├── libtasn1-6
    │   │   └── copyright
    │   ├── libtinfo5
    │   │   └── copyright
    │   ├── libwind0-heimdal
    │   │   └── copyright
    │   ├── libx11-xcb1
    │   │   └── copyright
    │   ├── libxau6
    │   │   └── copyright
    │   ├── libxcb-glx0
    │   │   └── copyright
    │   ├── libxcb-present0
    │   │   └── copyright
    │   ├── libxcb-sync1
    │   │   └── copyright
    │   ├── libxdamage1
    │   │   └── copyright
    │   ├── libxdmcp6
    │   │   └── copyright
    │   ├── libxext6
    │   │   └── copyright
    │   ├── libxfixes3
    │   │   └── copyright
    │   ├── libxrandr2
    │   │   └── copyright
    │   ├── libxrender1
    │   │   └── copyright
    │   ├── libxshmfence1
    │   │   └── copyright
    │   └── libxxf86vm1
    │       └── copyright
    └── icons
        └── hicolor
            └── 72x72
                └── apps
                    └── icon.png

64 directories, 143 files
```
Every file in `./usr/lib` is "symlinked" in `./usr/lib32`. I can hear sound.
EDIT: Of course `export LD_LIBRARY_PATH="$PWD/usr/lib32"`
EDIT 2: If I export `./usr/lib` as well, `./.runner-unwrapped` won't see the libraries for me.

> That's strange. Can you try to save the following file: (...)

Sure:
```
$ ./foo.sh 
./foo.sh
```

**Comment by Miepee** [comment]
can you diff your tree, so it's easier to see what you added new?
EDIT: if you do that, also please post it in the corresponding issue instead of here.


The result from the script is what was expected, so something weird is going on there

**Comment by Miepee** [comment]
Pushed d378132085dc866c13d0802b271a9776a0dccced which has an alternative way of executing the runner, lemme know if that works.

**Comment by Miepee** [comment]
> EDIT: Of course export LD_LIBRARY_PATH="$PWD/usr/lib32"

Quickly wanna note here that of course this is less than ideal to do and definitively not recommended.

**Comment by RancidJackalope** [comment]
> can you diff your tree, so it's easier to see what you added new?

EDIT: I still need to double check.
```
lib32
├── libasound.so.2 -> libasound.so.2.0.0
├── libasound.so.2.0.0
├── libopenal.so.1 -> libopenal.so.1.19.1
├── libopenal.so.1.19.1
├── libpulsecommon-15.99.so -> ../lib/i386-linux-gnu/pulseaudio/libpulsecommon-15.99.so
├── libpulse-simple.so.0 -> ../lib/i386-linux-gnu/libpulse-simple.so.0.1.1
├── libpulse-simple.so.0.1.1 -> ../lib/i386-linux-gnu/libpulse-simple.so.0.1.1
├── libpulse.so.0 -> ../lib/i386-linux-gnu/libpulse.so.0.24.1
├── libpulse.so.0.24.1 -> ../lib/i386-linux-gnu/libpulse.so.0.24.1
```

I tried d378132 and the same error:
```
$ ./AM2R.AppImage 
/tmp/.mount_AM2R.AQAvqBM/bin//runner: 5: exec: ./.runner-unwrapped: not found
```

> Quickly wanna note here that of course this is less than ideal to do and definitively not recommended.

I was not aware, not sure about alternatives, I'll be sure to search for them.
EDIT: Is `patchelf --set-rpath` acceptable enough? Because that worked fine for me right now.

**Comment by RancidJackalope** [comment]
All right, I got it. In the file `patcher.sh` I replaced the `readlink` command in the line 133 with `readlink -f` (or with `realpath`):
`radeonsi_sync_compile="true" exec "$(dirname "$(readlink -f "$0")")/.runner-unwrapped" "$@"`

Thank you very much for all the work you do for all of us, it's incommensurable.

**Comment by Miepee** [comment]
Thanks for the help with that too!
