### ISSUE TITLE
V 1.1

### ISSUE THREAD

**Issue by RancidJackalope** [Lojemiru/AM2R-Autopatcher-Linux#33]
I just noticed that the version shown in the title screen is not v1.5.5 but v1.1. I used the `patcher.sh`. I'm not sure about what's going on. Here is a screenshot:
![title](https://user-images.githubusercontent.com/101689912/193351583-35b622f7-998c-49f5-8d85-131227ce7b34.png)

----------------------------------------------------------------------------
commit: 56d7dd2d3612c42fc1de9644b8752512c0af51af
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

**Comment by RancidJackalope** [comment]
I got it. In the file `patcher.sh` replace the line 86:
`xdelta3 -dfs "$GAMEDIR/data.win" "$SCRIPT_DIR/data/game.xdelta" "$RESOURCES/game.unx"`
with this one:
`xdelta3 -dfs "$GAMEDIR/data.win" "$SCRIPT_DIR/data/game.xdelta" "$GAMEDIR/game.unx"`

**Comment by Miepee** [comment]
Replacing the path to GAMEDIR should not work, as the game data file / WAD needs to be in the "assets" folder which is where RESOURCES point to.
When i try to replicate this on 56d7dd2d3612c42fc1de9644b8752512c0af51af, it just works for me.

Can you share a log / which options you choose?

**Comment by RancidJackalope** [comment]
`./patcher.sh --os linux --appimage`

Log:
```
-------------------------------------------

AM2R 1.5.5 Shell Autopatching Utility

-------------------------------------------
AM2R_11.zip found!
Patching for Linux...
Applying AM2R xdelta patch...
Applying asset xdelta patch...
Cleaning up residual AM2R 1.1 files...
Formatting game directory...
Installing new datafiles...
Creating wrapper script to fix Mesa support...
Creating desktop file...
Creating AppImage...
Parallel mksquashfs: Using 4 processors
Creating 4.0 filesystem on /tmp/tmp.yY2BTwWCAU/AM2R.AppImage, block size 131072.

[=============================================================/] 1062/1062 100%

Exportable Squashfs 4.0 filesystem, gzip compressed, data block size 131072
	compressed data, compressed metadata, compressed fragments,
	compressed xattrs, compressed ids
	duplicates are removed
Filesystem size 83076.80 Kbytes (81.13 Mbytes)
	74.77% of uncompressed filesystem size (111109.90 Kbytes)
Inode table size 5589 bytes (5.46 Kbytes)
	38.94% of uncompressed inode table size (14354 bytes)
Directory table size 3445 bytes (3.36 Kbytes)
	40.51% of uncompressed directory table size (8504 bytes)
Number of duplicate files found 23
Number of inodes 337
Number of files 258
Number of fragments 29
Number of symbolic links  3
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 76
Number of ids (unique uids + gids) 1
Number of uids 1
	root (0)
Number of gids 1
	root (0)
/tmp/tmp.rAAtOM5Guf should be packaged as /tmp/tmp.yY2BTwWCAU/AM2R.AppImage

The operation was completed successfully. See you next mission!
```

**Comment by Miepee** [comment]
Cannot reproduce :/
Try adding 
```bash
		echo "$GAMEDIR"
		echo "$RESOURCES"
```
before line 86 and see what it spews out?

**Comment by RancidJackalope** [comment]
I just saw the problem. The original zip `AM2R_11.zip` already contains a file called `game.unx`. So reach this point in the script:
```
# This won't move the runner, because it doesn't have a dot
mv $GAMEDIR/*.* "$RESOURCES/"
```
then you overwrite the `game.unx` you just patched.
My change worked because it overwrites the old one and then gets moved to where it goes. Hope that helps.

**Comment by Miepee** [comment]
If your original AM2R_11 zip had a game.unx file, then that's an invalid 1.1 zip and thus not supported.
